# Generated by Django 4.1.5 on 2023-01-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_roupa', models.CharField(max_length=300)),
                ('cor', models.CharField(max_length=200)),
                ('tamanho', models.CharField(max_length=20)),
                ('preco', models.FloatField()),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
